spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308
    username: root
    password: top10isours
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect